{
	allCategories:{
		"babiesAndKids":{
			"diapersAndWipes":[],
			"babiesFashion":[],
			"girlsFashion":[],
			"boysFashion":[],
			"feedingAndNursing":[],
			"bathAndSkinCare":[],
			"momsAndMaternity":[],
			"babyGear":[],
			"healthAndSafety":[],
			"nursery":[],
			"babyDetergent":[],
			"Others":[],
		},
		"Cameras":{
			"car/DashCamera":[],
			"drones":[],
			"cctv/IP Camera":[],
			"Action Camera":[],
			"Camera Accessories":[],
			"Digital Camera":[],
			"OtherCamera":[],

		},
		"Digital Goods and Vouchers":{
			"Travel":[],
			"Dining":[],
			"Leisure and Entertainment":[],
			"Services":[],
			"Digital Currencies and Subscription Vourcers":[],
			"Others":[],
		},
		"Gaming":{
			"Console Gaming":[],
			"Computer Gaming":[],
			"Mobile Gaming":[],
			"Others":[],
		},
		"Groceries":{
			"Beverages":[],
			"Seasoning Staple Foods and Baking Ingredients":[],
			"Alcoholic Beverages":[],
			"Breakfast Food Snack and Sweet items":[],
			"Laundry and Household Product":[],
			"Superfoods and Healthy Foods":[],
			"Others":[],
		},
		"Health and Personal Care":{
			"Skin Care":[],
			"Bath and Body":[],
			"Whitening":[],
			"Health Supplements":[],
			"Mens Grooming":[],
			"Personal Care":[],
			"Hair":[],
			"Medical Supplies":[],
			"Slimming": [],
			"Suncare":[],
			"SexualWellness":[],
			"Others":[],
		},
		"Hobbies and Stationary":{
			"Musical Instruments":[],
			"Books":[],
			"Packaging and Wrapping":[],
			"School and Office Supplies":[],
			"Arts and crafts":[],
			"Religious Artifacts":[],
			"Paper Supplies":[],
			"Writing Materials":[],
			"Magazine and NewsPapers":[],
			"Others":[],
		},
		"Home and Living":{
			"Seasonal Decor":[],
			"Home Improvement":[],
			"Party and Event Supplies":[],
			"Furniture":[],
			"KitchenWare":[],
			"dinnerWare":[],
			"Storage and Organization":[],
			"Home Decor":[],
			"Lighting":[],
			"Beddings":[],
			"Bath":[],
			"Outdoor and Garden":[],
			"Bakeware":[],
			"Home Maintenance":[],
			"others":[],
		},
		"Home Appliances":{
			"Small Kitchen Appliances":[],
			"Cooling and Heating":[],
			"Vacuum Cleaners and Floor Care":[],
			"Garment Care":[],
			"Large Appliances":[],
			"Home Appliances Parts and Accessories":[],
			"Humidifiers and Air Purifies":[],
			"Others":[],
		},
		"Home Entertainment":{
			"Speakers and Karaoke":[],
			"Projectors":[],
			"TV Accessories":[],
			"Television":[],
			"Others":[],
		},
		"Laptops and Computers":{
			"USB Gadgets":[],
			"Computer Hardware":[],
			"Software":[],
			"Printer and Inks":[],
			"Storage":[],

		},
		"MakeUp and Fragrances":{
			"Eye Makeup":[],
			"Lip Makeup":[],
			"Fragrances":[],
			"Face Makeup":[],
			"Palettes and Makeup Sets":[],
			"Tools and Accessories":[],
			"Nails":[],
			"Others":[],
		},
		"Mens Apparel":{
			"Tops":[],
			"Jacket and Outerwear":[],
			"Underwear":[],
			"Shorts":[],
			"Pants":[],
			"Socks":[],
			"Hoodies and Sweatshirt":[],
			"others":[],
		},
		"Mens Bags and Accessories":{
			"Hats and Caps":[],
			"Wallets":[],
			"Eye Wear":[],
			"Accessories":[],
			"Jewelry":[],
			"Watches":[],
			"Mens bags":[],
			"Others":[],
			,
		"Mens Shoes":{
			"Loafer and Boat Shoes":[],
			"Sneakers":[],
			"Sandals and Flip-flops":[],
			"Boots":[],
			"Formal":[],
			"Shoe Care and Accessories":[],
		},
		"Mobiles and Accessories":{
			"Mobiles":[],
			"Accessories":[],
			"Portable Audio":[],
			"Power Banks and Chargers":[],
			"Tablets":[],
			"Wearables":[],
			"Others":[],
		},
		"Motors":{
			"Automotive Parts":[],
			"Exterior Car Accessories":[],
			"Interior Car Accessories":[],
			"Car Electronics":[],
			"Motorcycle and ATV Parts":[],
			"Motorcycle Accessories":[],
			"Car care and Detailing":[],
			"Motor Riding and Protective Gear":[],
			"Tools and Garage":[],
			"Oils Coolants and Fluids":[],
			"Car Services":[],
		},
		"Pets":{
			"Pet Care":[],
			"Pet Grooming Supplies":[],
			"Pet toys and Accessories":[],
			"Pet Essentails":[],
			"Pet Food and Treats":[],
			"Others":[],
		},
		"Sports and Travel":{
			"Exercise and Fitness":[],
			"Travel Bags":[],
			"Travel Accessories":[],
			"Mens ActiveWear":[],
			"Womens ActiveWear":[],
			"Sports Bag":[],
			"Camping and Hiking":[],
			"Cycling Skates and Scooters":[],
			"Team Sports":[],
			"Racket Sports":[],
			"Leisure Sports and Game Room":[],
			"Outdoor Recreation":[],
			"Golf":[],
			"Water Sports":[],
			"Weather Protection":[],
			"Winter Sports Gear":[],
			"Boxing and MMA":[],
			"Cockfighting":[],
			"Others":[],
		},
		"Toys Games and Collectibles":{
			"Boards and Famliy Games":[],
			"Electronic Toys":[],
			"Collectibles":[],
			"Education Toys":[],
			"Dolls":[],
			"Dress Up and Pretend":[],
			"Sports and Outdoor Toys":[],
			"Celebrity Merchandise":[],
			"others":[],
		},
		"Womens Accessories":{
			"Watches":[],
			"Jewelry":[],
			"Wallet and Pouches":[],
			"Eyewear":[],
			"Hair Accessories":[],
			"Hats and Caps":[],
			"Belts and Scarves":[],
			"Fine Jewelry":[],
			"Watch and Jewelry":[],
			"Watch and Jewelry Organizers":[],
			"Others":[]
		},
		"Womens Apparel":{
			"Dresses":[],
			"Tops":[],
			"Tees":[],
			"Pants":[],
			"Skirts":[],
			"Shorts":[],
			"Jackets and Outwear":[],
			"Jumpsuit and Rumpers":[],
			"Lingerie and Nightware":[],
			"Swimsuits":[],
			"Coordinates":[],
			"Socks and Stockings":[],
			"Plus size":[],
			"Sweater and Cardigans":[],
			"Others":[],

		},
		"Womens Bags":{
			"Shoulder Bags":[],
			"Tote Bags":[],
			"Handbags":[],
			"Clutches":[],
			"Backpacks":[],
			"Drawstring Bags":[],
			"Accessories":[],
			"Others":[],
		},
		"Womens shoes":{
			"Flats":[],
			"Heels":[],
			"Wedges and Platforms":[],
			"Sneakers":[],
			"Flip-flops":[],
			"Shoe care and accessories":[],
			"Boots":[],
			"Others":[],
		}


	}
}